### ISSUE TITLE
USER STORY: Payment information

### ISSUE THREAD

**Issue by Charte-dot** [Charte-dot/Coder-Space#21]
As a Shopper I can enter my payment details hassle free, So I can checkout my purchases quickly and easily
  
# Acceptance Criteria:
 - Acceptance Criteria 1: User clicks on checkout to complete payment form
 - Acceptance Criteria 2: Success message visible on completion of payment process

# Tasks
  - [X] Task 1: Install and set up stripe
  - [X] Task 2: Create template for payment form
  - [X] Task 3: Set up webhooks to check success/ errors in payment process
