### ISSUE TITLE
USER STORY: Subscription to newsletter

### ISSUE THREAD

**Issue by Charte-dot** [Charte-dot/Coder-Space#30]
As a Shopper I want to be able to sign up to a newsletter, So I can keep up to date with new products that become available
# Acceptance Criteria
 - Acceptance Criteria 1: User can sign up with email to a newsletter subscription service on the site.

# Tasks
  - [X] Task 1: Create template
  - [X] Task 2: Create model
  - [X] Task 3: Create View
  - [X] Task 4: Create url
